from google.genai import types

from config.gemini_client import client, MODEL_NAME
from models.overall_model import LoanDecisionResponse


class LoanAgent:

    def __init__(self):
        with open("prompts/overall.txt", "r", encoding="utf-8") as f:
            self.prompt = f.read()

    def evaluate(self, combined_response: str) -> LoanDecisionResponse:
        """
        Evaluate loan eligibility from outputs of all previous agents.

        Args:
            combined_response:
                JSON string generated by the Master Agent.

        Returns:
            LoanDecisionResponse
        """

        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=[
                self.prompt,
                combined_response,
            ],
            config=types.GenerateContentConfig(
                temperature=0,
                response_mime_type="application/json",
                response_schema=LoanDecisionResponse,
            ),
        )

        return response.parsed